### ISSUE TITLE
¿API o Bot?

### ISSUE THREAD

**Issue by JmZero** [JmZero/TFG_Covid-19_reports#1]
Se ha hablado de poder llevar a cabo una de las dos opciones para este TFG, pero creo que depende un poco de lo que se quiera obtener como resultado del mismo. Lo que se pretende obtener es un proyecto que nos proporcione datos relativos al estado de la enfermedad Covid-19, ¿pero que nos puede llegar a proporcionar mas datos?

En primer lugar los datos que usaremos tanto para la API como para el Bot serán los mismo, lo único que varía es el como se representan. Para la API se tiene claro que las llamadas a la misma nos devolverán la respuesta en formato JSON. Para el bot, podremos hacerle el mismo tipo de peticiones de dato, pero a su vez, un bot nos podría aportar ciertas ventajas frente a una API. Por ejemplo, a diferencia de la API, un bot podría devolvernos los datos solicitados acompañados de una gráfica, y mostrarnos por medio de diferentes gráficas la evolución, estimación o diferentes variables de la pandemia. Para que la API llegara a mostrarnos gráficas tendríamos que desarrollar algo (como por ejemplo una web) que consuma los resultados de las peticiones a nuestra API.

**Comment by JJ** [comment]
Está bien que te plantees este tipo de cosas desde el principio, pero antes todavía tienes que plantearte las historias de usuario. Una vez que tengas una, o varias, historias de usuario esta pregunta se resuelve sola. El tipo de usuario(s) que tienes en mente van a necesitar una, otra o las dos.
Mira cualquier recurso sobre como elaborar las historias de usuario, pero generalmente partes de un problema que resolver y a partir de ahí lo vas refinando (¿para quién quieres resolver el problema?, por ejemplo)

**Comment by JmZero** [comment]
He tardado más en añadir las historias de usuario porque era la primera vez que trabajaba en SCRUM, pero ya están listas. Me gustaría que las pudieras revisar de cara a crear las diferentes actividades asociadas a las mismas antes de nada por si es necesario hacer algún cambio, que supongo que habrá que hacer mas de uno porque es la primera vez que hago esto.
Ahora al hacer las historias de usuario tengo claro que lo mas viable seria hacer un bot, aunque puede hacerse que en algunos casos este consuma los datos que devuelva una api. Pero la principal idea recae en un bot.

**Comment by JJ** [comment]
Tienes que ver si te sirven a ti. Le echaré un vistazo si puedo, pero en
principio las HUs en sí son difíciles de evaluar sin ver el código y tests
a los que dan lugar. Simplemente mantenlas coherentes con el problema a
resolver, y el resto ya se irá viendo. Una HU tampoco tiene que ser
perfecta. A veces te das cuenta de que le falta algo, y tienes que crear
otra para desambiguarlo.

**Comment by JJ** [comment]
¿Has creado ya las historias de usuario? Mira por ejemplo [estas](https://github.com/cecimerelo/VizYourData/issues/13) para ver cómo se estructuran y se crean.

**Comment by JJ** [comment]
En todo caso, API y bot no son excluyentes. Un bot (y más cosas) pueden consumir un API, por ejemplo.

**Comment by JmZero** [comment]
Encontré varias formas de crear las historias de usuario.
En el modelo que presenté en la memoria esta hecho de manera en la que cada HU tiene los siguientes campos:
- **ID** : Identificador único de la historia de usuario.
- **Nombre** : Nombre asignado a la historia de usuario
- **Prioridad** : Importancia a la hora de llevar a cabo en el desarrollo, pudiendo
ser alta, media o baja
- **Riesgo** : Importancia en relación al conjunto del proyecto, indicando así en
caso de fallo el daño provocado, pudiendo ser alto, medio o bajo. .
- **Descripción** : Explicación de la historia de usuario, dejando clara la idea
de la misma
- **Validación** : Condiciones que se han de cumplir para dar la historia por
finalizada.

¿Seria más conveniente crear las diferentes HU y las tareas asociadas a las mismas como Issues para que cuando se finalicen las tareas señalarlos en la propia HU?

**Comment by JJ** [comment]
Las HUs son siempre issues, sí. Las tareas asociadas pueden ser otros issues
